# Generated by Django 3.2 on 2021-04-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('communicationId', models.AutoField(primary_key=True, serialize=False)),
                ('communicationTitle', models.CharField(max_length=250)),
                ('communicationContent', models.TextField()),
                ('communicationImg', models.CharField(max_length=250, null=True)),
                ('communicationDate', models.DateTimeField(auto_now=True)),
                ('communicationViews', models.IntegerField(default=0)),
                ('communicationCategory', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.TextField()),
                ('communicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.communication')),
            ],
        ),
    ]
