# Generated by Django 3.2 on 2021-04-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('qnaId', models.AutoField(primary_key=True, serialize=False)),
                ('qnaTitle', models.CharField(max_length=250)),
                ('qnaContent', models.TextField()),
                ('qnaImg', models.CharField(max_length=250, null=True)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='QnA_Reply',
            fields=[
                ('replyId', models.AutoField(primary_key=True, serialize=False)),
                ('replyContent', models.TextField()),
                ('qnaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.qna')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
