# Generated by Django 3.2 on 2021-04-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookTitle', models.CharField(max_length=250)),
                ('bookWritter', models.CharField(max_length=50, null=True)),
                ('bookIntro', models.TextField(null=True)),
                ('bookLike', models.IntegerField(default=0)),
                ('bookPublisher', models.CharField(max_length=50, null=True)),
                ('bookImg', models.CharField(max_length=250, null=True)),
                ('bookSubscribe', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(default='bookshelf', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BookArticle',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('articleTitle', models.CharField(max_length=250)),
                ('articleContent', models.TextField()),
                ('articleImg', models.CharField(max_length=250, null=True)),
                ('articleDate', models.DateTimeField(auto_now=True)),
                ('articleViews', models.IntegerField(default=0)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='SignBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmarkId', models.AutoField(primary_key=True, serialize=False)),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookarticle')),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
