# Generated by Django 3.2 on 2021-04-21 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('memoId', models.AutoField(primary_key=True, serialize=False)),
                ('memoTitle', models.CharField(max_length=250)),
                ('memoContent', models.TextField()),
                ('memoDate', models.DateTimeField(auto_now=True)),
                ('memoImg', models.CharField(max_length=250, null=True)),
                ('articleId', models.ForeignKey(default='bookshelf', on_delete=django.db.models.deletion.SET_DEFAULT, to='book.bookarticle')),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
