# Generated by Django 3.2 on 2021-04-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20210423_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='articleId',
        ),
    ]
